"""Table 4 — Exp 3 volume-comparison.

Reads per-(benchmark, config, method) CSVs from
``examples/FlowConformal/experiments/exp3_synthetic/outputs/`` and
produces a single LaTeX table with one row per benchmark and columns
for each (method × config) cell. Cell shows ``mean (stdev)`` of the
volume ratio = predicted_volume / true_reach_volume.

The starset baseline has no config axis so it occupies a single
column rather than three.

Run with::

    /home/sasakis/miniconda3/envs/n2v/bin/python -m \\
        examples.FlowConformal.paper.tables.tab4_exp3_volume_comparison
"""
from __future__ import annotations

import argparse
import csv
import statistics
from pathlib import Path

import numpy as np

PAPER_DIR = Path(__file__).resolve().parent.parent
EXP3_OUTPUTS = (
    PAPER_DIR.parent / 'experiments' / 'exp3_synthetic' / 'outputs'
)
DEFAULT_OUT = (
    Path(__file__).resolve().parent / 'outputs' / 'tab4_exp3_volume.tex'
)

# Display order (low-dim → high-dim) and labels.
BENCHES = [
    ('2d_banana',  r'2d\_banana'),
    ('synth_2d',   r'synth\_2d'),
    ('3d_banana',  r'3d\_banana'),
    ('synth_3d',   r'synth\_3d'),
    ('synth_5d',   r'synth\_5d'),
    ('synth_10d',  r'synth\_10d'),
    ('synth_20d',  r'synth\_20d'),
]
CONFIGS = ('small', 'default', 'large')


def _floats(rows, key):
    out = []
    for r in rows:
        v = r.get(key, '').strip()
        if not v:
            continue
        try:
            x = float(v)
        except ValueError:
            continue
        if np.isfinite(x):
            out.append(x)
    return out


def _read(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with open(path) as f:
        return list(csv.DictReader(f))


def _ratio_summary(bench: str, method: str,
                   config: str) -> tuple[float, float]:
    """Return (mean_ratio, std_ratio); NaN if no data."""
    if method == 'ours':
        path = EXP3_OUTPUTS / f'exp3_{bench}_flow_unsat_ours_{config}.csv'
        ratio_col = 'volume_ratio'
    elif method == 'hashemi_clipping':
        path = (
            EXP3_OUTPUTS
            / f'exp3_{bench}_unsat_hashemi_clipping_{config}.csv'
        )
        ratio_col = 'volume_ratio_closedform'
    elif method == 'starset':
        path = EXP3_OUTPUTS / f'exp3_{bench}_unsat_starset_approx.csv'
        ratio_col = 'volume_ratio'
    else:
        raise ValueError(f'unknown method: {method}')
    rows = _read(path)
    ratios = _floats(rows, ratio_col)
    if not ratios:
        return float('nan'), float('nan')
    if len(ratios) == 1:
        return ratios[0], 0.0
    return statistics.mean(ratios), statistics.stdev(ratios)


def _fmt_cell(mean: float, std: float) -> str:
    """Format the ratio mean as a LaTeX cell.

    Pre-1k: 2 decimals or rounded integer. ≥1k: scientific notation
    with one digit after the point. NaN cells render as a single
    em-dash. The ``std`` argument is currently ignored — the table
    reports mean only to keep the body compact.
    """
    del std  # intentional: we only show the mean.
    if not np.isfinite(mean):
        return r'\multicolumn{1}{c}{$-$}'
    if mean < 100:
        return f'{mean:.2f}'
    if mean < 1000:
        return f'{mean:.0f}'
    m_exp = int(np.floor(np.log10(max(mean, 1e-300))))
    m_mant = mean / (10 ** m_exp)
    return f'{m_mant:.1f}{{\\scriptsize\\,e{m_exp}}}'


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)

    # Build the table body row by row.
    body_rows: list[str] = []
    for bench, label in BENCHES:
        cells = []
        for method in ('ours', 'hashemi_clipping'):
            for cfg in CONFIGS:
                m, s = _ratio_summary(bench, method, cfg)
                cells.append(_fmt_cell(m, s))
        # starset (no config axis)
        m, s = _ratio_summary(bench, 'starset', 'default')
        cells.append(_fmt_cell(m, s))
        body_rows.append(f'{label} & ' + ' & '.join(cells) + r' \\')

    n_cols = 1 + 6 + 1   # benchmark + 3*ours + 3*hashemi + starset
    col_spec = 'l' + 'r' * 6 + 'r'

    lines = []
    lines.append('% Auto-generated by examples/FlowConformal/paper/tables/'
                 'tab4_exp3_volume_comparison.py')
    lines.append('% Required LaTeX packages: booktabs.')
    lines.append(r'\begin{table*}[!t]')
    lines.append(r'\centering')
    lines.append(
        r'\caption{Volume-comparison on Exp~3 synthetic benchmarks. '
        r'Each cell reports the mean volume ratio over 5 seeds, '
        r'where ratio $= \mathrm{vol}(R_{\mathrm{predicted}}) / '
        r'\mathrm{vol}(R_{\mathrm{true}})$. Smaller is tighter; '
        r'$1.00$ is exact. The reach-set ground truth comes from '
        r'either a closed-form determinant (synth\_$N$d, '
        r'identity-activation 1-Lipschitz nets) or a cached '
        r'$N{=}10^7$-sample MC estimate (the bananas). Sample-budget '
        r'configs are small/medium/large = $m{=}1{\rm k}/8{\rm k}/16{\rm k}$. '
        r'\textit{Star (approx)} is the n2v sound star-set '
        r'over-approximation baseline; it has no $m$ axis.}'
    )
    lines.append(r'\label{tab:exp3_volume}')
    lines.append(r'\setlength{\tabcolsep}{4pt}')
    lines.append(r'\renewcommand{\arraystretch}{1.05}')
    lines.append(r'\footnotesize')
    lines.append(r'\begin{tabular}{' + col_spec + '}')
    lines.append(r'\toprule')
    lines.append(
        r' & \multicolumn{3}{c}{\textbf{Ours}} '
        r'& \multicolumn{3}{c}{\textbf{Hashemi-CLIP}} '
        r'& \textbf{Star} \\'
    )
    lines.append(r'\cmidrule(lr){2-4} \cmidrule(lr){5-7}')
    lines.append(
        r'\textbf{Benchmark} & small & medium & large '
        r'& small & medium & large & approx \\'
    )
    lines.append(r'\midrule')
    lines.extend(body_rows)
    lines.append(r'\bottomrule')
    lines.append(r'\end{tabular}')
    lines.append(r'\end{table*}')

    args.output.write_text('\n'.join(lines) + '\n')
    print(f'Wrote {args.output}')


if __name__ == '__main__':
    main()
